using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using JetBrains.Annotations;
using Nuke.Common.Tooling;


namespace Nuke.Common.Tools.FluentMigrator
{
    /// <summary>
    ///   <p>The command-line interface (CLI) tools for Fluent Migrator perform design-time development tasks. For example, they apply migrations, apply <a href="https://fluentmigrator.github.io/articles/migration-example.html">migrations</a>. The commands are an extension to the cross-platform <a href="https://fluentmigrator.github.io/articles/runners/dotnet-fm.html">dotnet</a> command, which is part of the <a href="https://www.microsoft.com/net/core">.NET Core SDK</a>. These tools work with .NET Core projects.<para/>If you're using Visual Studio, we recommend the <a href="https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell">Package Manager Console tools</a> instead:<para/><ul><li>They automatically work with the current project selected in the Package Manager Console without requiring that you manually switch directories.</li><li>They automatically open files generated by a command after the command is completed.</li></ul></p>
    ///   <p>For more details, visit the <a href="https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet">official website</a>.</p>
    /// </summary>
    [PublicAPI]
    public static partial class FluentMigratorTask
    {

        /// <summary>
        ///     Path to the Fluent Migrator executable.
        /// </summary>
        public static string FluentMigratorPath =>
            ToolPathResolver.TryGetEnvironmentExecutable("FLUENTMIGRATOR_EXE") ??
            ToolPathResolver.GetPathExecutable("dotnet");

        public static Action<OutputType, string> FluentMigratorLogger { get; set; } = ProcessTasks.DefaultLogger;

        #region List migrations
        
        /// <summary>
        ///   <p>The <c>dotnet fm list migrations</c> command is used to list applied and pending migrations.</p>
        ///   <p>For more details, visit the <a href="https://fluentmigrator.github.io/articles/runners/dotnet-fm.html#command-structure">official website</a>.</p>
        /// </summary>
        /// <remarks>
        ///   <p>This is a <a href="http://www.nuke.build/docs/authoring-builds/cli-tools.html#fluent-apis">CLI wrapper with fluent API</a> that allows to modify the following arguments:</p>
        ///   <ul>
        ///     <li><c>--connection</c> via <see cref="FluentMigratorSetting.ConnectionString"/></li>
        ///     <li><c>--no-connection</c> via <see cref="FluentMigratorSetting.NoConnectionString"/></li>
        ///     <li><c>--assembly</c> via <see cref="FluentMigratorSetting.Assembly"/></li>
        ///     <li><c>--namespace</c> via <see cref="FluentMigratorSetting.Namespace"/></li>
        ///     <li><c>--preview</c> via <see cref="FluentMigratorSetting.Preview"/></li>
        ///     <li><c>--profile</c> via <see cref="FluentMigratorSetting.Profile"/></li>
        ///     <li><c>--timeout</c> via <see cref="FluentMigratorSetting.Timeout"/></li>
        ///     <li><c>--output</c> via <see cref="FluentMigratorSetting.Output"/></li>
        ///     <li><c>--nested</c> via <see cref="FluentMigratorSetting.Nested"/></li>
        ///     <li><c>--working-directory</c> via <see cref="FluentMigratorSetting.WorkingDirectory"/></li>
        ///     <li><c>--tag</c> via <see cref="FluentMigratorSetting.Tag"/></li>
        ///     <li><c>--allow-breaking-changes</c> via <see cref="FluentMigratorSetting.AllowBreakingChanges"/></li>
        ///     <li><c>--processor</c> via <see cref="FluentMigratorSetting.Processor"/></li>
        ///     <li><c>--verbose</c> via <see cref="FluentMigratorSetting.Verbose"/></li>
        ///   </ul>
        /// </remarks>
        public static IReadOnlyCollection<Output> FluentMigratorListMigrations(FluentMigratorListMigrationsSetting toolSetting = null)
        {
            toolSetting = toolSetting ?? new FluentMigratorListMigrationsSetting();
            using (var process = ProcessTasks.StartProcess(toolSetting))
            {
                process.AssertZeroExitCode();
                return process.Output;
            }
        }
        
        /// <summary>
        ///   <p>The <c>dotnet fm list migrations</c> command is used to list applied and pending migrations.</p>
        ///   <p>For more details, visit the <a href="https://fluentmigrator.github.io/articles/runners/dotnet-fm.html#command-structure">official website</a>.</p>
        /// </summary>
        /// <remarks>
        ///   <p>This is a <a href="http://www.nuke.build/docs/authoring-builds/cli-tools.html#fluent-apis">CLI wrapper with fluent API</a> that allows to modify the following arguments:</p>
        ///   <ul>
        ///     <li><c>--connection</c> via <see cref="FluentMigratorSetting.ConnectionString"/></li>
        ///     <li><c>--no-connection</c> via <see cref="FluentMigratorSetting.NoConnectionString"/></li>
        ///     <li><c>--assembly</c> via <see cref="FluentMigratorSetting.Assembly"/></li>
        ///     <li><c>--namespace</c> via <see cref="FluentMigratorSetting.Namespace"/></li>
        ///     <li><c>--preview</c> via <see cref="FluentMigratorSetting.Preview"/></li>
        ///     <li><c>--profile</c> via <see cref="FluentMigratorSetting.Profile"/></li>
        ///     <li><c>--timeout</c> via <see cref="FluentMigratorSetting.Timeout"/></li>
        ///     <li><c>--output</c> via <see cref="FluentMigratorSetting.Output"/></li>
        ///     <li><c>--nested</c> via <see cref="FluentMigratorSetting.Nested"/></li>
        ///     <li><c>--working-directory</c> via <see cref="FluentMigratorSetting.WorkingDirectory"/></li>
        ///     <li><c>--tag</c> via <see cref="FluentMigratorSetting.Tag"/></li>
        ///     <li><c>--allow-breaking-changes</c> via <see cref="FluentMigratorSetting.AllowBreakingChanges"/></li>
        ///     <li><c>--processor</c> via <see cref="FluentMigratorSetting.Processor"/></li>
        ///     <li><c>--verbose</c> via <see cref="FluentMigratorSetting.Verbose"/></li>
        ///   </ul>
        /// </remarks>
        public static IEnumerable<(FluentMigratorListMigrationsSetting Settings, IReadOnlyCollection<Output> Output)> FluentMigratorListMigrations(CombinatorialConfigure<FluentMigratorListMigrationsSetting> configurator, int degreeOfParallelism = 1, bool completeOnFailure = false)
        {
            return configurator.Invoke(FluentMigratorListMigrations, FluentMigratorLogger, degreeOfParallelism, completeOnFailure);
        }
        
        /// <summary>
        ///   <p>The <c>dotnet fm list migrations</c> command is used to list applied and pending migrations.</p>
        ///   <p>For more details, visit the <a href="https://fluentmigrator.github.io/articles/runners/dotnet-fm.html#command-structure">official website</a>.</p>
        /// </summary>
        /// <remarks>
        ///   <p>This is a <a href="http://www.nuke.build/docs/authoring-builds/cli-tools.html#fluent-apis">CLI wrapper with fluent API</a> that allows to modify the following arguments:</p>
        ///   <ul>
        ///     <li><c>--connection</c> via <see cref="FluentMigratorSetting.ConnectionString"/></li>
        ///     <li><c>--no-connection</c> via <see cref="FluentMigratorSetting.NoConnectionString"/></li>
        ///     <li><c>--assembly</c> via <see cref="FluentMigratorSetting.Assembly"/></li>
        ///     <li><c>--namespace</c> via <see cref="FluentMigratorSetting.Namespace"/></li>
        ///     <li><c>--preview</c> via <see cref="FluentMigratorSetting.Preview"/></li>
        ///     <li><c>--profile</c> via <see cref="FluentMigratorSetting.Profile"/></li>
        ///     <li><c>--timeout</c> via <see cref="FluentMigratorSetting.Timeout"/></li>
        ///     <li><c>--output</c> via <see cref="FluentMigratorSetting.Output"/></li>
        ///     <li><c>--nested</c> via <see cref="FluentMigratorSetting.Nested"/></li>
        ///     <li><c>--working-directory</c> via <see cref="FluentMigratorSetting.WorkingDirectory"/></li>
        ///     <li><c>--tag</c> via <see cref="FluentMigratorSetting.Tag"/></li>
        ///     <li><c>--allow-breaking-changes</c> via <see cref="FluentMigratorSetting.AllowBreakingChanges"/></li>
        ///     <li><c>--processor</c> via <see cref="FluentMigratorSetting.Processor"/></li>
        ///     <li><c>--verbose</c> via <see cref="FluentMigratorSetting.Verbose"/></li>
        ///   </ul>
        /// </remarks>
        public static IReadOnlyCollection<Output> FluentMigratorListMigrations(Configure<FluentMigratorListMigrationsSetting> configurator)
        {
            return FluentMigratorListMigrations(configurator(new FluentMigratorListMigrationsSetting()));
        }
        #endregion

        #region Rollback

        #region All

        /// <summary>
        ///   <p>The <c>dotnet fm rollback all</c> command is used to rollback all migrations.</p>
        ///   <p>For more details, visit the <a href="https://fluentmigrator.github.io/articles/runners/dotnet-fm.html#command-structure">official website</a>.</p>
        /// </summary>
        /// <remarks>
        ///   <p>This is a <a href="http://www.nuke.build/docs/authoring-builds/cli-tools.html#fluent-apis">CLI wrapper with fluent API</a> that allows to modify the following arguments:</p>
        ///   <ul>
        ///     <li><c>--connection</c> via <see cref="FluentMigratorSetting.ConnectionString"/></li>
        ///     <li><c>--no-connection</c> via <see cref="FluentMigratorSetting.NoConnectionString"/></li>
        ///     <li><c>--assembly</c> via <see cref="FluentMigratorSetting.Assembly"/></li>
        ///     <li><c>--namespace</c> via <see cref="FluentMigratorSetting.Namespace"/></li>
        ///     <li><c>--preview</c> via <see cref="FluentMigratorSetting.Preview"/></li>
        ///     <li><c>--profile</c> via <see cref="FluentMigratorSetting.Profile"/></li>
        ///     <li><c>--timeout</c> via <see cref="FluentMigratorSetting.Timeout"/></li>
        ///     <li><c>--output</c> via <see cref="FluentMigratorSetting.Output"/></li>
        ///     <li><c>--nested</c> via <see cref="FluentMigratorSetting.Nested"/></li>
        ///     <li><c>--working-directory</c> via <see cref="FluentMigratorSetting.WorkingDirectory"/></li>
        ///     <li><c>--tag</c> via <see cref="FluentMigratorSetting.Tag"/></li>
        ///     <li><c>--allow-breaking-changes</c> via <see cref="FluentMigratorSetting.AllowBreakingChanges"/></li>
        ///     <li><c>--processor</c> via <see cref="FluentMigratorSetting.Processor"/></li>
        ///     <li><c>--verbose</c> via <see cref="FluentMigratorSetting.Verbose"/></li>
        ///     <li><c>--transaction-mode</c> via <see cref="FluentMigratorRollbackSetting.TransactionMode"/></li>
        ///   </ul>
        /// </remarks>
        public static IReadOnlyCollection<Output> FluentMigratorRollbackAll(FluentMigratorRollbackAllSetting toolSetting = null)
        {
            toolSetting = toolSetting ?? new FluentMigratorRollbackAllSetting();
            using (var process = ProcessTasks.StartProcess(toolSetting))
            {
                process.AssertZeroExitCode();
                return process.Output;
            } 
        }
        
        /// <summary>
        ///   <p>The <c>dotnet fm rollback all</c> command is used to rollback all migrations.</p>
        ///   <p>For more details, visit the <a href="https://fluentmigrator.github.io/articles/runners/dotnet-fm.html#command-structure">official website</a>.</p>
        /// </summary>
        /// <remarks>
        ///   <p>This is a <a href="http://www.nuke.build/docs/authoring-builds/cli-tools.html#fluent-apis">CLI wrapper with fluent API</a> that allows to modify the following arguments:</p>
        ///   <ul>
        ///     <li><c>--connection</c> via <see cref="FluentMigratorSetting.ConnectionString"/></li>
        ///     <li><c>--no-connection</c> via <see cref="FluentMigratorSetting.NoConnectionString"/></li>
        ///     <li><c>--assembly</c> via <see cref="FluentMigratorSetting.Assembly"/></li>
        ///     <li><c>--namespace</c> via <see cref="FluentMigratorSetting.Namespace"/></li>
        ///     <li><c>--preview</c> via <see cref="FluentMigratorSetting.Preview"/></li>
        ///     <li><c>--profile</c> via <see cref="FluentMigratorSetting.Profile"/></li>
        ///     <li><c>--timeout</c> via <see cref="FluentMigratorSetting.Timeout"/></li>
        ///     <li><c>--output</c> via <see cref="FluentMigratorSetting.Output"/></li>
        ///     <li><c>--nested</c> via <see cref="FluentMigratorSetting.Nested"/></li>
        ///     <li><c>--working-directory</c> via <see cref="FluentMigratorSetting.WorkingDirectory"/></li>
        ///     <li><c>--tag</c> via <see cref="FluentMigratorSetting.Tag"/></li>
        ///     <li><c>--allow-breaking-changes</c> via <see cref="FluentMigratorSetting.AllowBreakingChanges"/></li>
        ///     <li><c>--processor</c> via <see cref="FluentMigratorSetting.Processor"/></li>
        ///     <li><c>--verbose</c> via <see cref="FluentMigratorSetting.Verbose"/></li>
        ///     <li><c>--transaction-mode</c> via <see cref="FluentMigratorRollbackSetting.TransactionMode"/></li>
        ///   </ul>
        /// </remarks>
        public static IEnumerable<(FluentMigratorRollbackAllSetting Settings, IReadOnlyCollection<Output> Output)> FluentMigratorRollbackAll(CombinatorialConfigure<FluentMigratorRollbackAllSetting> configurator, int degreeOfParallelism = 1, bool completeOnFailure = false)
        {
            return configurator.Invoke(FluentMigratorRollbackAll, FluentMigratorLogger, degreeOfParallelism, completeOnFailure); 
        }
        
        /// <summary>
        ///   <p>The <c>dotnet fm rollback all</c> command is used to rollback all migrations.</p>
        ///   <p>For more details, visit the <a href="https://fluentmigrator.github.io/articles/runners/dotnet-fm.html#command-structure">official website</a>.</p>
        /// </summary>
        /// <remarks>
        ///   <p>This is a <a href="http://www.nuke.build/docs/authoring-builds/cli-tools.html#fluent-apis">CLI wrapper with fluent API</a> that allows to modify the following arguments:</p>
        ///   <ul>
        ///     <li><c>--connection</c> via <see cref="FluentMigratorSetting.ConnectionString"/></li>
        ///     <li><c>--no-connection</c> via <see cref="FluentMigratorSetting.NoConnectionString"/></li>
        ///     <li><c>--assembly</c> via <see cref="FluentMigratorSetting.Assembly"/></li>
        ///     <li><c>--namespace</c> via <see cref="FluentMigratorSetting.Namespace"/></li>
        ///     <li><c>--preview</c> via <see cref="FluentMigratorSetting.Preview"/></li>
        ///     <li><c>--profile</c> via <see cref="FluentMigratorSetting.Profile"/></li>
        ///     <li><c>--timeout</c> via <see cref="FluentMigratorSetting.Timeout"/></li>
        ///     <li><c>--output</c> via <see cref="FluentMigratorSetting.Output"/></li>
        ///     <li><c>--nested</c> via <see cref="FluentMigratorSetting.Nested"/></li>
        ///     <li><c>--working-directory</c> via <see cref="FluentMigratorSetting.WorkingDirectory"/></li>
        ///     <li><c>--tag</c> via <see cref="FluentMigratorSetting.Tag"/></li>
        ///     <li><c>--allow-breaking-changes</c> via <see cref="FluentMigratorSetting.AllowBreakingChanges"/></li>
        ///     <li><c>--processor</c> via <see cref="FluentMigratorSetting.Processor"/></li>
        ///     <li><c>--verbose</c> via <see cref="FluentMigratorSetting.Verbose"/></li>
        ///     <li><c>--transaction-mode</c> via <see cref="FluentMigratorRollbackSetting.TransactionMode"/></li>
        ///   </ul>
        /// </remarks>
        public static IReadOnlyCollection<Output> FluentMigratorRollbackAll(Configure<FluentMigratorRollbackAllSetting> configurator)
        {
            return FluentMigratorRollbackAll(configurator(new FluentMigratorRollbackAllSetting()));
        }
        
        #endregion
        
        #region By

        /// <summary>
        ///   <p>The <c>dotnet fm rollback all</c> command is used to rollback by N steps.</p>
        ///   <p>For more details, visit the <a href="https://fluentmigrator.github.io/articles/runners/dotnet-fm.html#command-structure">official website</a>.</p>
        /// </summary>
        /// <remarks>
        ///   <p>This is a <a href="http://www.nuke.build/docs/authoring-builds/cli-tools.html#fluent-apis">CLI wrapper with fluent API</a> that allows to modify the following arguments:</p>
        ///   <ul>
        ///     <li><c>n</c> via <see cref="FluentMigratorRollbackBySetting.Step"/></li>
        ///     <li><c>--connection</c> via <see cref="FluentMigratorSetting.ConnectionString"/></li>
        ///     <li><c>--no-connection</c> via <see cref="FluentMigratorSetting.NoConnectionString"/></li>
        ///     <li><c>--assembly</c> via <see cref="FluentMigratorSetting.Assembly"/></li>
        ///     <li><c>--namespace</c> via <see cref="FluentMigratorSetting.Namespace"/></li>
        ///     <li><c>--preview</c> via <see cref="FluentMigratorSetting.Preview"/></li>
        ///     <li><c>--profile</c> via <see cref="FluentMigratorSetting.Profile"/></li>
        ///     <li><c>--timeout</c> via <see cref="FluentMigratorSetting.Timeout"/></li>
        ///     <li><c>--output</c> via <see cref="FluentMigratorSetting.Output"/></li>
        ///     <li><c>--nested</c> via <see cref="FluentMigratorSetting.Nested"/></li>
        ///     <li><c>--working-directory</c> via <see cref="FluentMigratorSetting.WorkingDirectory"/></li>
        ///     <li><c>--tag</c> via <see cref="FluentMigratorSetting.Tag"/></li>
        ///     <li><c>--allow-breaking-changes</c> via <see cref="FluentMigratorSetting.AllowBreakingChanges"/></li>
        ///     <li><c>--processor</c> via <see cref="FluentMigratorSetting.Processor"/></li>
        ///     <li><c>--verbose</c> via <see cref="FluentMigratorSetting.Verbose"/></li>
        ///   </ul>
        /// </remarks>
        public static IReadOnlyCollection<Output> FluentMigratorRollbackBy(FluentMigratorRollbackBySetting toolSetting = null)
        {
            toolSetting = toolSetting ?? new FluentMigratorRollbackBySetting();
            using (var process = ProcessTasks.StartProcess(toolSetting))
            {
                process.AssertZeroExitCode();
                return process.Output;
            } 
        }
        
        /// <summary>
        ///   <p>The <c>dotnet fm rollback all</c> command is used to rollback by N steps.</p>
        ///   <p>For more details, visit the <a href="https://fluentmigrator.github.io/articles/runners/dotnet-fm.html#command-structure">official website</a>.</p>
        /// </summary>
        /// <remarks>
        ///   <p>This is a <a href="http://www.nuke.build/docs/authoring-builds/cli-tools.html#fluent-apis">CLI wrapper with fluent API</a> that allows to modify the following arguments:</p>
        ///   <ul>
        ///     <li><c>n</c> via <see cref="FluentMigratorRollbackBySetting.Step"/></li>
        ///     <li><c>--connection</c> via <see cref="FluentMigratorSetting.ConnectionString"/></li>
        ///     <li><c>--no-connection</c> via <see cref="FluentMigratorSetting.NoConnectionString"/></li>
        ///     <li><c>--assembly</c> via <see cref="FluentMigratorSetting.Assembly"/></li>
        ///     <li><c>--namespace</c> via <see cref="FluentMigratorSetting.Namespace"/></li>
        ///     <li><c>--preview</c> via <see cref="FluentMigratorSetting.Preview"/></li>
        ///     <li><c>--profile</c> via <see cref="FluentMigratorSetting.Profile"/></li>
        ///     <li><c>--timeout</c> via <see cref="FluentMigratorSetting.Timeout"/></li>
        ///     <li><c>--output</c> via <see cref="FluentMigratorSetting.Output"/></li>
        ///     <li><c>--nested</c> via <see cref="FluentMigratorSetting.Nested"/></li>
        ///     <li><c>--working-directory</c> via <see cref="FluentMigratorSetting.WorkingDirectory"/></li>
        ///     <li><c>--tag</c> via <see cref="FluentMigratorSetting.Tag"/></li>
        ///     <li><c>--allow-breaking-changes</c> via <see cref="FluentMigratorSetting.AllowBreakingChanges"/></li>
        ///     <li><c>--processor</c> via <see cref="FluentMigratorSetting.Processor"/></li>
        ///     <li><c>--verbose</c> via <see cref="FluentMigratorSetting.Verbose"/></li>
        ///   </ul>
        /// </remarks>
        public static IEnumerable<(FluentMigratorRollbackBySetting Settings, IReadOnlyCollection<Output> Output)> FluentMigratorRollbackBy(CombinatorialConfigure<FluentMigratorRollbackBySetting> configurator, int degreeOfParallelism = 1, bool completeOnFailure = false)
        {
            return configurator.Invoke(FluentMigratorRollbackBy, FluentMigratorLogger, degreeOfParallelism, completeOnFailure); 
        }
        
        /// <summary>
        ///   <p>The <c>dotnet fm rollback all</c> command is used to rollback by N steps.</p>
        ///   <p>For more details, visit the <a href="https://fluentmigrator.github.io/articles/runners/dotnet-fm.html#command-structure">official website</a>.</p>
        /// </summary>
        /// <remarks>
        ///   <p>This is a <a href="http://www.nuke.build/docs/authoring-builds/cli-tools.html#fluent-apis">CLI wrapper with fluent API</a> that allows to modify the following arguments:</p>
        ///   <ul>
        ///     <li><c>n</c> via <see cref="FluentMigratorRollbackBySetting.Step"/></li>
        ///     <li><c>--connection</c> via <see cref="FluentMigratorSetting.ConnectionString"/></li>
        ///     <li><c>--no-connection</c> via <see cref="FluentMigratorSetting.NoConnectionString"/></li>
        ///     <li><c>--assembly</c> via <see cref="FluentMigratorSetting.Assembly"/></li>
        ///     <li><c>--namespace</c> via <see cref="FluentMigratorSetting.Namespace"/></li>
        ///     <li><c>--preview</c> via <see cref="FluentMigratorSetting.Preview"/></li>
        ///     <li><c>--profile</c> via <see cref="FluentMigratorSetting.Profile"/></li>
        ///     <li><c>--timeout</c> via <see cref="FluentMigratorSetting.Timeout"/></li>
        ///     <li><c>--output</c> via <see cref="FluentMigratorSetting.Output"/></li>
        ///     <li><c>--nested</c> via <see cref="FluentMigratorSetting.Nested"/></li>
        ///     <li><c>--working-directory</c> via <see cref="FluentMigratorSetting.WorkingDirectory"/></li>
        ///     <li><c>--tag</c> via <see cref="FluentMigratorSetting.Tag"/></li>
        ///     <li><c>--allow-breaking-changes</c> via <see cref="FluentMigratorSetting.AllowBreakingChanges"/></li>
        ///     <li><c>--processor</c> via <see cref="FluentMigratorSetting.Processor"/></li>
        ///     <li><c>--verbose</c> via <see cref="FluentMigratorSetting.Verbose"/></li>
        ///   </ul>
        /// </remarks>
        public static IReadOnlyCollection<Output> FluentMigratorRollbackBy(Configure<FluentMigratorRollbackBySetting> configurator)
        {
            return FluentMigratorRollbackBy(configurator(new FluentMigratorRollbackBySetting()));
        }
        
        #endregion
        
        #region To

        /// <summary>
        ///   <p>The <c>dotnet fm rollback all</c> command is used to rollback to N version.</p>
        ///   <p>For more details, visit the <a href="https://fluentmigrator.github.io/articles/runners/dotnet-fm.html#command-structure">official website</a>.</p>
        /// </summary>
        /// <remarks>
        ///   <p>This is a <a href="http://www.nuke.build/docs/authoring-builds/cli-tools.html#fluent-apis">CLI wrapper with fluent API</a> that allows to modify the following arguments:</p>
        ///   <ul>
        ///     <li><c>n</c> via <see cref="FluentMigratorRollbackBySetting.Step"/></li>
        ///     <li><c>--connection</c> via <see cref="FluentMigratorSetting.ConnectionString"/></li>
        ///     <li><c>--no-connection</c> via <see cref="FluentMigratorSetting.NoConnectionString"/></li>
        ///     <li><c>--assembly</c> via <see cref="FluentMigratorSetting.Assembly"/></li>
        ///     <li><c>--namespace</c> via <see cref="FluentMigratorSetting.Namespace"/></li>
        ///     <li><c>--preview</c> via <see cref="FluentMigratorSetting.Preview"/></li>
        ///     <li><c>--profile</c> via <see cref="FluentMigratorSetting.Profile"/></li>
        ///     <li><c>--timeout</c> via <see cref="FluentMigratorSetting.Timeout"/></li>
        ///     <li><c>--output</c> via <see cref="FluentMigratorSetting.Output"/></li>
        ///     <li><c>--nested</c> via <see cref="FluentMigratorSetting.Nested"/></li>
        ///     <li><c>--working-directory</c> via <see cref="FluentMigratorSetting.WorkingDirectory"/></li>
        ///     <li><c>--tag</c> via <see cref="FluentMigratorSetting.Tag"/></li>
        ///     <li><c>--allow-breaking-changes</c> via <see cref="FluentMigratorSetting.AllowBreakingChanges"/></li>
        ///     <li><c>--processor</c> via <see cref="FluentMigratorSetting.Processor"/></li>
        ///     <li><c>--verbose</c> via <see cref="FluentMigratorSetting.Verbose"/></li>
        ///   </ul>
        /// </remarks>
        public static IEnumerable<(FluentMigratorRollbackToSetting Settings, IReadOnlyCollection<Output> Output)> FluentMigratorRollbackTo(CombinatorialConfigure<FluentMigratorRollbackToSetting> configurator, int degreeOfParallelism = 1, bool completeOnFailure = false)
        {
            return configurator.Invoke(FluentMigratorRollbackTo, FluentMigratorLogger, degreeOfParallelism, completeOnFailure); 
        }

        /// <summary>
        ///   <p>The <c>dotnet fm rollback all</c> command is used to rollback to N version.</p>
        ///   <p>For more details, visit the <a href="https://fluentmigrator.github.io/articles/runners/dotnet-fm.html#command-structure">official website</a>.</p>
        /// </summary>
        /// <remarks>
        ///   <p>This is a <a href="http://www.nuke.build/docs/authoring-builds/cli-tools.html#fluent-apis">CLI wrapper with fluent API</a> that allows to modify the following arguments:</p>
        ///   <ul>
        ///     <li><c>to</c> via <see cref="FluentMigratorRollbackToSetting.Version"/></li>
        ///     <li><c>--connection</c> via <see cref="FluentMigratorSetting.ConnectionString"/></li>
        ///     <li><c>--no-connection</c> via <see cref="FluentMigratorSetting.NoConnectionString"/></li>
        ///     <li><c>--assembly</c> via <see cref="FluentMigratorSetting.Assembly"/></li>
        ///     <li><c>--namespace</c> via <see cref="FluentMigratorSetting.Namespace"/></li>
        ///     <li><c>--preview</c> via <see cref="FluentMigratorSetting.Preview"/></li>
        ///     <li><c>--profile</c> via <see cref="FluentMigratorSetting.Profile"/></li>
        ///     <li><c>--timeout</c> via <see cref="FluentMigratorSetting.Timeout"/></li>
        ///     <li><c>--output</c> via <see cref="FluentMigratorSetting.Output"/></li>
        ///     <li><c>--nested</c> via <see cref="FluentMigratorSetting.Nested"/></li>
        ///     <li><c>--working-directory</c> via <see cref="FluentMigratorSetting.WorkingDirectory"/></li>
        ///     <li><c>--tag</c> via <see cref="FluentMigratorSetting.Tag"/></li>
        ///     <li><c>--allow-breaking-changes</c> via <see cref="FluentMigratorSetting.AllowBreakingChanges"/></li>
        ///     <li><c>--processor</c> via <see cref="FluentMigratorSetting.Processor"/></li>
        ///     <li><c>--verbose</c> via <see cref="FluentMigratorSetting.Verbose"/></li>
        ///   </ul>
        /// </remarks>
        public static IReadOnlyCollection<Output> FluentMigratorRollbackTo(FluentMigratorRollbackToSetting toolSetting = null)
        {
            toolSetting = toolSetting ?? new FluentMigratorRollbackToSetting();
            using (var process = ProcessTasks.StartProcess(toolSetting))
            {
                process.AssertZeroExitCode();
                return process.Output;
            } 
        }

        /// <summary>
        ///   <p>The <c>dotnet fm rollback all</c> command is used to rollback to N version.</p>
        ///   <p>For more details, visit the <a href="https://fluentmigrator.github.io/articles/runners/dotnet-fm.html#command-structure">official website</a>.</p>
        /// </summary>
        /// <remarks>
        ///   <p>This is a <a href="http://www.nuke.build/docs/authoring-builds/cli-tools.html#fluent-apis">CLI wrapper with fluent API</a> that allows to modify the following arguments:</p>
        ///   <ul>
        ///     <li><c>to</c> via <see cref="FluentMigratorRollbackToSetting.Version"/></li>
        ///     <li><c>--connection</c> via <see cref="FluentMigratorSetting.ConnectionString"/></li>
        ///     <li><c>--no-connection</c> via <see cref="FluentMigratorSetting.NoConnectionString"/></li>
        ///     <li><c>--assembly</c> via <see cref="FluentMigratorSetting.Assembly"/></li>
        ///     <li><c>--namespace</c> via <see cref="FluentMigratorSetting.Namespace"/></li>
        ///     <li><c>--preview</c> via <see cref="FluentMigratorSetting.Preview"/></li>
        ///     <li><c>--profile</c> via <see cref="FluentMigratorSetting.Profile"/></li>
        ///     <li><c>--timeout</c> via <see cref="FluentMigratorSetting.Timeout"/></li>
        ///     <li><c>--output</c> via <see cref="FluentMigratorSetting.Output"/></li>
        ///     <li><c>--nested</c> via <see cref="FluentMigratorSetting.Nested"/></li>
        ///     <li><c>--working-directory</c> via <see cref="FluentMigratorSetting.WorkingDirectory"/></li>
        ///     <li><c>--tag</c> via <see cref="FluentMigratorSetting.Tag"/></li>
        ///     <li><c>--allow-breaking-changes</c> via <see cref="FluentMigratorSetting.AllowBreakingChanges"/></li>
        ///     <li><c>--processor</c> via <see cref="FluentMigratorSetting.Processor"/></li>
        ///     <li><c>--verbose</c> via <see cref="FluentMigratorSetting.Verbose"/></li>
        ///   </ul>
        /// </remarks>
        public static IReadOnlyCollection<Output> FluentMigratorRollbackTo(Configure<FluentMigratorRollbackToSetting> configurator)
        {
            return FluentMigratorRollbackTo(configurator(new FluentMigratorRollbackToSetting()));
        }
        
        #endregion

        #endregion
    }
}
